title: Dancing with Data
description: "A little blog to document things I've learnt, things I've done and things I'd like to do"
author: Cam Cairns
github: https://github.com/camcairns
about: "Love all things data. Experience in data engineering, model building and development, machine learning, data viz, automation and model deployment"
disqus_shortname: dancingwithdata
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    - icon: fa-skype
      link: "cam.cairns1"
    - icon: fa-twitter
      link: "https://twitter.com/CairnsCam"
    - icon: fa-linkedin
      link: "https://uk.linkedin.com/in/cameron-cairns-6975a172"
    # - icon: fa-stack-exchange
    #   link: "#"

share:
  twitter_username: cairnscam
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/camcairns
    # - text: XML Feed
    #   url: /feed.xml

url: "https://camcairns.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist